# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/

language: cpp

env:
  global:
  - CATCH2_REPO=${HOME}/Catch2

before_cache:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -mindepth 1 -delete; fi

cache:
  directories:
  - ${HOME}/Library/Caches/Homebrew
  - /usr/local/Homebrew
  - ${CATCH2_REPO}

dist:
- bionic


matrix:
  include:
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DUSE64=ON \
                    -DTCK_ENABLE_MEMCHECK_TESTS=ON \
                    -DTCK_ENABLE_COVREACH_TESTS=ON \
                    -DTCK_ENABLE_EXPLORE_TESTS=OFF \
                    -DTCK_ENABLE_UNITTESTS=OFF \
                    -DTCK_ENABLE_SIMPLE_NR_TESTS=OFF \
                    -DTCK_ENABLE_BUGFIXES_TESTS=OFF"
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DTCK_ENABLE_MEMCHECK_TESTS=ON \
                    -DTCK_ENABLE_COVREACH_TESTS=ON \
                    -DTCK_ENABLE_EXPLORE_TESTS=OFF \
                    -DTCK_ENABLE_UNITTESTS=OFF \
                    -DTCK_ENABLE_SIMPLE_NR_TESTS=OFF \
                    -DTCK_ENABLE_BUGFIXES_TESTS=OFF"
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DTCK_ENABLE_MEMCHECK_TESTS=ON \
                    -DTCK_ENABLE_COVREACH_TESTS=OFF \
                    -DTCK_ENABLE_EXPLORE_TESTS=ON \
                    -DTCK_ENABLE_UNITTESTS=OFF \
                    -DTCK_ENABLE_SIMPLE_NR_TESTS=OFF \
                    -DTCK_ENABLE_BUGFIXES_TESTS=OFF"
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF  -DTCK_ENABLE_MEMCHECK_TESTS=ON"
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DUSE16=ON -DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF  -DTCK_ENABLE_MEMCHECK_TESTS=ON"
  - os: linux
    compiler: gcc
    env: TEST_CONF="-DUSE64=ON -DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF  -DTCK_ENABLE_MEMCHECK_TESTS=ON"

  - os: linux
    compiler: clang
    env: TEST_CONF="-DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF  -DTCK_ENABLE_MEMCHECK_TESTS=ON"

  - os: osx
    compiler: gcc
    env: TEST_CONF="-DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF -DTCK_ENABLE_MEMCHECK_TESTS=OFF"
  - os: osx
    compiler: gcc
    env: TEST_CONF="-DUSE64=ON -DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF -DTCK_ENABLE_MEMCHECK_TESTS=OFF"
  - os: osx
    compiler: clang
    env: TEST_CONF="-DTCK_ENABLE_COVREACH_TESTS=OFF -DTCK_ENABLE_EXPLORE_TESTS=OFF -DTCK_ENABLE_MEMCHECK_TESTS=OFF"

install:
- . ./ci-scripts/setenv-common.sh
- ./ci-scripts/install-${TRAVIS_OS_NAME}.sh
- . ./ci-scripts/setenv-${TRAVIS_OS_NAME}.sh
- ./ci-scripts/show-config.sh

script:
- ./ci-scripts/build-and-test.sh

addons:
  apt:
    packages:
    - libboost-all-dev
    - valgrind
    update: true
  homebrew:
    packages:
    - boost
    - bison@3.7
    update: true

notifications:
  email: true

